[package]
name = "zeal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"
bevy_egui = "0.21"
eframe = "0.23.0"
egui = "0.23.0"
env_logger = "0.10.0"
